# Generated by Django 4.1.5 on 2023-03-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterField(
            model_name='buy',
            name='total',
            field=models.IntegerField(verbose_name='Total P.C.'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='total_prod',
            field=models.IntegerField(verbose_name='Total Productos'),
        ),
    ]
