# Generated by Django 4.1.5 on 2023-02-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ganancy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ganancia'),
        ),
    ]
