# Generated by Django 4.1.5 on 2023-03-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_alter_buy_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cant',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
