# Generated by Django 4.1.7 on 2023-03-07 21:51

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_ganancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', validators=[product.models.validate_image_size], verbose_name='Foto del Producto'),
        ),
    ]
