# Generated by Django 4.1.5 on 2023-04-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('type_sale', models.CharField(blank=True, choices=[('Venta', 'Venta'), ('Merma', 'Merma'), ('Personal', 'Personal')], default='Venta', max_length=10, null=True, verbose_name='Tipo de Salida')),
                ('observation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observación')),
                ('total_prod', models.IntegerField(default=0, verbose_name='Total Productos')),
                ('total_sale', models.IntegerField(default=0, verbose_name='Total')),
                ('output_products', models.JSONField(blank=True, null=True, verbose_name='Productos')),
                ('is_canceled', models.BooleanField(blank=True, default=False, null=True, verbose_name='Anulado')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-id'],
            },
        ),
    ]
