# Generated by Django 4.1.5 on 2023-02-05 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_sale', models.DateField(verbose_name='Fecha/Hora')),
                ('type_sale', models.CharField(choices=[('Venta', 'Venta'), ('Merma', 'Merma'), ('Personal', 'Personal')], default='Venta', max_length=10, verbose_name='Tipo de Salida')),
                ('observation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observación')),
                ('cant', models.IntegerField(verbose_name='Cantidad')),
                ('total_prod', models.IntegerField(default=0, verbose_name='Total Productos')),
                ('total_sale', models.IntegerField(default=0, verbose_name='Total')),
                ('output_products', models.JSONField(blank=True, null=True, verbose_name='Productos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
