# Generated by Django 4.1.5 on 2023-02-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_sale',
            field=models.DateTimeField(verbose_name='Fecha/Hora'),
        ),
    ]
