# Generated by Django 4.1.5 on 2023-02-09 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_remove_sale_cant_alter_sale_date_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_sale',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 16, 46, 0, 273374), verbose_name='Fecha/Hora'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='type_sale',
            field=models.CharField(blank=True, choices=[('Venta', 'Venta'), ('Merma', 'Merma'), ('Personal', 'Personal')], default='Venta', max_length=10, null=True, verbose_name='Tipo de Salida'),
        ),
    ]
