# Generated by Django 4.1.5 on 2023-02-11 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_alter_sale_date_sale_alter_sale_type_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_sale',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 21, 45, 49, 314459), verbose_name='Fecha/Hora'),
        ),
    ]
