# Generated by Django 4.0 on 2023-02-12 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_alter_sale_date_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_sale',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 0, 27, 54, 762630), verbose_name='Fecha/Hora'),
        ),
    ]
