# Generated by Django 4.1.5 on 2023-02-13 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_alter_sale_date_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='date_sale',
        ),
    ]
