# Generated by Django 4.1.5 on 2023-02-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_remove_sale_date_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-id'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddField(
            model_name='sale',
            name='is_canceled',
            field=models.BooleanField(blank=True, null=True, verbose_name='Anulado'),
        ),
    ]
