# Generated by Django 4.1.5 on 2023-02-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_alter_sale_options_sale_is_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='is_canceled',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Anulado'),
        ),
    ]
